//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StopGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR SALA.
        /// </summary>
        public static string btnCreateRoom {
            get {
                return ResourceManager.GetString("btnCreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INGLES.
        /// </summary>
        public static string btnEnglish {
            get {
                return ResourceManager.GetString("btnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR DEL JUEGO.
        /// </summary>
        public static string btnExitGame {
            get {
                return ResourceManager.GetString("btnExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIRSE A SALA.
        /// </summary>
        public static string btnJoinRoom {
            get {
                return ResourceManager.GetString("btnJoinRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR SESIÓN.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIAR COMO INVITADO.
        /// </summary>
        public static string btnPlayAsGuest {
            get {
                return ResourceManager.GetString("btnPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTIDAS PUBLICAS.
        /// </summary>
        public static string btnPublicGames {
            get {
                return ResourceManager.GetString("btnPublicGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGISTRAR.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESPAÑOL.
        /// </summary>
        public static string btnSpain {
            get {
                return ResourceManager.GetString("btnSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENVIAR CÓDIGO.
        /// </summary>
        public static string btnVerifyEmail {
            get {
                return ResourceManager.GetString("btnVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SE HA ENVIADO UN CÓDIGO PARA VERIFICAR SU CORREO ELECTRÓNICO.
        /// </summary>
        public static string lbCodeSubmission {
            get {
                return ResourceManager.GetString("lbCodeSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIGURACIÓN.
        /// </summary>
        public static string lbConfiguration {
            get {
                return ResourceManager.GetString("lbConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CORREO ELECTRONICO:.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERIFICACIÓN DE CORREO ELECTRONICO.
        /// </summary>
        public static string lbEmailVerification {
            get {
                return ResourceManager.GetString("lbEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AYUDA.
        /// </summary>
        public static string lbHelp {
            get {
                return ResourceManager.GetString("lbHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDIOMA:.
        /// </summary>
        public static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE:.
        /// </summary>
        public static string lbName {
            get {
                return ResourceManager.GetString("lbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONTRASEÑA:.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B A S T A.
        /// </summary>
        public static string lbTitle {
            get {
                return ResourceManager.GetString("lbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE DE USUARIO:.
        /// </summary>
        public static string lbUserName {
            get {
                return ResourceManager.GetString("lbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERFIL DE USUARIO.
        /// </summary>
        public static string lbUserPerfile {
            get {
                return ResourceManager.GetString("lbUserPerfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NÚMERO DE VERIFICACIÓN: .
        /// </summary>
        public static string lbVerificationNumber {
            get {
                return ResourceManager.GetString("lbVerificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BASTA LIS.
        /// </summary>
        public static string windowTile {
            get {
                return ResourceManager.GetString("windowTile", resourceCulture);
            }
        }
    }
}
